config/routes.rb
AdminvTestApp::Application.routes.draw do
  match 'edit' => 'sample#edit', :as => "sample_edit"
  root :to => 'sample#index' 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  layout 'adminv'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/views/adminv/_footer.html.haml
Adminv template by 
= link_to("Involved", "http://involved.com.au", :target => "_blank")

app/views/adminv/_header.html.haml
%h1
  = link_to_if request.fullpath != root_path, "Adminv", root_url
%h3
  (Rails CMS template)

app/views/adminv/_javascripts.html.erb
<!-- Add your own JS here -->
<%#= javascript_include_tag "adminv/adminv-custom" %>

<!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID 
<script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
-->

app/views/adminv/_javascripts_footer.html.erb
<!-- Add your own JS here -->
<%#= javascript_include_tag "adminv/adminv-custom" %>

<!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID 
<script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
-->

app/views/adminv/_meta.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta name="description" content="Adminv CMS">
<meta name="author" content="Admiv CMS">

<%- if @no_index -%>
	<meta name="robots" content="noindex" />
<%- end -%>

<!-- IE -->
<!--[if IE]><meta http-equiv="imagetoolbar" content="no" /><![endif]-->

<!-- IE9 -->

<!-- Facebook -->
<!--
<meta property="fb:app_id" content=""/>
<meta property="og:title" content=""/>
<meta property="og:site_name" content="Adminv"/>
<meta property="og:image" content=""/>
<meta property="og:url" content=""/>
<meta property="og:type" content=""/>
-->

<!-- Mobile browser -->
<!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->

app/views/adminv/_primary_navigation.html.erb
<%- if defined?(Menumatic) -%>
	<%= render :navigation => "admin", :level => :primary, :id => "site-menu" %>
	<%= render :navigation => "user", :id => "settings-menu" %>
<%- else -%>
  <ul class="navigation admin active level_1 depth_1" id="site-menu">
    <li class="active"><%= link_to "Block", root_path%></li>
    <li class="inactive"><%= link_to "Forms", sample_edit_path %></li>
    <li class="inactive"><%= link_to "Log-in", "sample_login_path" %></li>
  </ul>
  <ul class="navigation user inactive level_1 depth_1" id="settings-menu">
    <li class="account"><%= link_to "Account", "javascript:void(0)" %></li>
    <li class="settings"><%= link_to "settings", "javascript:void(0)" %></li>
    <li class="logout"><%= link_to "Sign out", "javascript:void(0)" %></li>
  </ul><!-- #settings-menu -->
<%- end -%>

app/views/adminv/_primary_navigation.html.haml
- if defined?(Menumatic)
  = render :navigation => "admin", :level => :primary, :id => "site-menu"
  = render :navigation => "user", :id => "settings-menu"
- else
  %ul#site-menu
    %li= link_to "Dashboard", "javascript:void(0)"
  %ul#settings-menu
    %li.account= link_to "Account", "javascript:void(0)"
    %li.settings= link_to "settings", "javascript:void(0)"
    %li.logout= link_to "Sign out", "javascript:void(0)"

app/views/adminv/_secondary_navigation.html.haml
=# render :navigation => 'admin', :level => :secondary

app/views/adminv/_side_tabs.html.haml
%ul.navigation.active
  %li.active= link_to "Content", "#"
  %li.inactive= link_to "Archived promos", "#"

app/views/adminv/_user.html.haml
%dl.account
  %dt <span>Logged in as</span> Adminv User
  %dd.role (Super Administrator)
  %dd.gravatar= image_tag("adminv/gravatar.jpg", { :alt => "Gravatar" })

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adminv Test App</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sample/_form.html.haml
= simple_form_for :user, :html => {:novalidate => true} do |f|
  = adminv_container do |container|
    = container.content do |content|
      .block-inner
        %p 
          Adminv has been developed using '[simple_form](https://github.com/plataformatec/simple_form)' to handle it's forms. Adminv will in future be form builder agnostic but for now its best to use [simple_form](https://github.com/plataformatec/simple_form) and be sure to set `config.wrapper_tag = :li` in `config/initalizers/simple_form.rb`.
        %ul
          = f.input :xsmall, :input_html => {:class => "xsmall"}, :label => "Extra small"
          = f.input :small, :input_html => {:class => "small"}, :disabled => true
          = f.input :medium, :input_html => {:class => "medium error"}
          = f.input :large, :input_html => {:class => "large"}
          = f.input :xlarge, :input_html => {:class => "xlarge"}
          = f.input :date, :label => "Date", :order => [:day, :month, :year], :as => :date, :start_year => 1997, :end_year => Date.today.year + 2
          = f.input :description, :as => :text
          = f.collection_check_boxes :options, [[true, 'Yes'] ,[false, 'No']], :first, :last, :label => "what"
          = f.input :age, :collection => 18..60, :prompt => "Choose an age"
          = f.collection_radio :options, [[true, 'Yes'] ,[false, 'No']], :first, :last
          = f.input :Upload, :hint => "(This is a hint)"

  =# sidebar_right :test

app/views/sample/edit.html.haml
- title("Edit fake form template") 

=# back_block

.block-title
  %h1= "Edit: title goes here"

= render :partial => 'form'

app/views/sample/examples/_block_controls_tableless.haml
= simple_form_for :user, :html => {:novalidate => true} do |f|
  = adminv_container :width => :with_sidebar do |container|
    = container.content "Dogs" do |content|
      = content.header ""
      .block-inner
        %strong First Name: 
        = Faker::Name.first_name
        <br />
      
        %strong Last Name:
        = Faker::Name.last_name
        <br />
      
        %strong Email:
        = Faker::Internet.email
        <br />
      
        %strong Username:
        = Faker::Internet.user_name

      .block-controls
        .block-actions
          = button_group do
            = button_link_to "Edit Dog", "#"
            = negative_button_link_to "Delete Dog", "#", :method => "delete", :confirm => "Are you sure?"
            
    = container.content "Cats" do |content|
      = content.header ""
      .block-inner
        %strong First Name: 
        = Faker::Name.first_name
        <br />

        %strong Last Name:
        = Faker::Name.last_name
        <br />

        %strong Email:
        = Faker::Internet.email
        <br />

        %strong Username:
        = Faker::Internet.user_name

      .block-controls
        .block-actions
          = button_group do
            = button_link_to "Edit Cat", "#"
            = negative_button_link_to "Delete Cat", "#", :method => "delete", :confirm => "Are you sure?"

app/views/sample/examples/_table_basic.html.haml
= simple_form_for :user, :html => {:novalidate => true} do |f|
  = adminv_container :width => :with_sidebar do |container|
    = container.table do |table|
      = table.header "Users"
      .table
        .header-group
          .row
            .col= f.check_box :action
            .col ID
            .col First Name
            .col Last Name
            .col Email
            .col Username
            .col &nbsp;
        =# empty_row @releases, "releases"
        .row-group
          - (1...25).to_a.each do |index|
            .row
              .col= f.check_box :action
              .col= index
              .col= Faker::Name.first_name
              .col= Faker::Name.last_name
              .col= Faker::Internet.email
              .col= Faker::Internet.user_name
              .col.actions
                = button_group do
                  = pill_button_link_to "Show", "#", :title => "show", :target => "_blank"
                  = pill_button_link_to "Edit", "#", :title => "edit"
                  = negative_pill_trash_button_link_to "Delete", "#", :title => "destroy", :method => :delete, :confirm => "Are you sure?"

      .block-controls
        %ul.block-actions
          = f.input :age, :collection => ['Delete', 'Publish'], :prompt => "Select an action...", :label => false
    
        %nav.block-pagination
          %ul
            %li= link_to "&laquo;".html_safe, "#"
            %li= link_to "1", "#"
            %li= link_to "2", "#", :class => "active"
            %li= link_to "3", "#"
            %li= link_to "4", "#"
            %li= link_to "5", "#"
            %li= link_to "6", "#"
            %li= link_to "&raquo;".html_safe, "#"

app/views/sample/index.html.erb
	<section class="sidetabs block grid_3 tabs"><section class="block-container">
	<div class="block-content">
		<h3>Manage</h3>
		<ul class="navigation admin active level_1 depth_1">
			<li class="active"><a href="/manage/releases">Releases</a></li>
			<li class="inactive"><a href="/manage/scores">Scores</a></li>
		</ul>
		<div class="actions">
			<a href="/manage/releases/new" class="add icon button">New Release</a>
			<a href="/manage/plates/new/our_music" class="add icon button">New Plate</a>
		</div>
	</div>
	</section></section>
	<section class="block grid_9 tabs"><section class="block-container">
	<div class="block-header">
		<h3 class="block-description">Content</h3>
		<ul class="block-toggles">
		</ul>
	</div>
	<div class="block-table">
		<div class='table'>
			<div class='header-group'>
				<div class='row'>
					<div class='col'>
						Description
					</div>
					<div class='col'>
						Summary
					</div>
					<div class='col'>
						Last Modified
					</div>
					<div class='col'>
						&nbsp;
					</div>
				</div>
			</div>
			<div class='row-group'>
				<div class='row'>
					<div class='col'>
						Introduction
					</div>
					<div class='col'>
						Dive in here for samples of our music and where...
					</div>
					<div class='col'>
						14 days ago
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/manage/plates/our_music-introduction/edit" class="pill button">Edit</a>
							<a href="/manage/plates/our_music-introduction" class="pill button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</section></section>
	<section class="block grid_9 tabs"><section class="block-container">
	<div class="block-header">
		<h3 class="block-description">Releases</h3>
		<ul class="block-toggles">
		</ul>
	</div>
	<div class="block-table">
		<div class='table'>
			<div class='header-group'>
				<div class='row'>
					<div class='col'>
						Title
					</div>
					<div class='col'>
						Format
					</div>
					<div class='col'>
						Publisher
					</div>
					<div class='col'>
						Tracks
					</div>
					<div class='col'>
						Released
					</div>
					<div class='col'>
						&nbsp;
					</div>
				</div>
			</div>
			<div class='row-group'>
				<div class='row'>
					<div class='col'>
						Extraordinary Tale
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						13
					</div>
					<div class='col'>
						2011, Jul 29
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/extraordinary-tale" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/extraordinary-tale/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/extraordinary-tale" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						Feels Like Spring
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						12
					</div>
					<div class='col'>
						2010, Apr 16
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/feels-like-spring" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/feels-like-spring/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/feels-like-spring" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						The Idea of North - Live at the Powerhouse
					</div>
					<div class='col'>
						DVD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						15
					</div>
					<div class='col'>
						2007, Aug 18
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/the-idea-of-north-live-at-the-powerhouse" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/the-idea-of-north-live-at-the-powerhouse/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/the-idea-of-north-live-at-the-powerhouse" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						The Idea of North - Live at the Powerhouse
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						15
					</div>
					<div class='col'>
						2007, Jul 1
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/the-idea-of-north-live-at-the-powerhouse-1" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/the-idea-of-north-live-at-the-powerhouse-1/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/the-idea-of-north-live-at-the-powerhouse-1" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						The Gospel Project
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						KI Entertainment
					</div>
					<div class='col'>
						13
					</div>
					<div class='col'>
						2006, Mar 6
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/the-gospel-project" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/the-gospel-project/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/the-gospel-project" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						Evidence
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						12
					</div>
					<div class='col'>
						2004, May 14
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/evidence" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/evidence/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/evidence" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
				<div class='row'>
					<div class='col'>
						Here &amp; Now
					</div>
					<div class='col'>
						CD
					</div>
					<div class='col'>
						ABC Jazz
					</div>
					<div class='col'>
						11
					</div>
					<div class='col'>
						2003, Oct 15
					</div>
					<div class='col actions'>
						<div class="button-group">
							<a href="/our_music/here-and-now" class="pill button" target="_blank" title="show">Show</a>
							<a href="/manage/releases/here-and-now/edit" class="pill button" title="edit">Edit</a>
							<a href="/manage/releases/here-and-now" class="danger pill trash icon button" data-confirm="Are you sure?" data-method="delete" rel="nofollow" title="destroy">Delete</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	</section></section>

app/views/sample/index.html.haml
- title "Users", "Manage"

- content_for :sidebar_left do
  = add_button_link_to "New User", "#"

-#.block-form
  = adminv_container do |container|
    = container.table "Accordions" do |table|
      = table.header ""
      .table.accordion
        .header-group
          .row
            .col ID
            .col First Name
            .col Last Name
            .col Email
            .col Username
            .col &nbsp;
        .row-group
          - (1...10).to_a.each do |index|
            .row
              .col= index
              .col= Faker::Name.first_name
              .col= Faker::Name.last_name
              .col= Faker::Internet.email
              .col= Faker::Internet.user_name
              .col.actions
                = button_group do
                  = edit_button_link_to "Edit preview", "#", :class => "accordion-toggle"
                  =# remove_row("#")
              .details
                %ul.table
                  %li This is an accordion aaaight!!
        .footer-group
          .row
            .col Col 1
            .col Col 2
            .col Col 3
            .col Col 4
            .col Col 5
            .col Col 6

  
    = container.table "Sortable" do |table|
      = table.header ""
      .table.sortable.accordion
        .header-group
          .row
            .col Order
            .col First Name
            .col Last Name
            .col Email
            .col Username
            .col &nbsp;
        .row-group
          - (1...10).to_a.each do |index|
            .row
              .col.sort-handle
              .col= Faker::Name.first_name
              .col= Faker::Name.last_name
              .col= Faker::Internet.email
              .col= Faker::Internet.user_name
              .col.actions
                = button_group do
                  = pill_button_link_to "Show", "#", :title => "show", :target => "_blank"
                  = pill_button_link_to "Edit", "#", :title => "edit"
                  = negative_pill_trash_button_link_to "Delete", "#", :title => "destroy", :method => :delete, :confirm => "Are you sure?"
      .block-controls
        .block-actions
          =# add_row(f, :tracks, :form_builder_local => :form, :label => "Add new track", :object => @release.tracks.build, :target => "#track-listing.table .row-group")

    = container.table "Sortable Accordions" do |table|
      = table.header ""
      .table.accordion.sortable
        .header-group
          .row
            .col Order
            .col First Name
            .col Last Name
            .col Email
            .col Username
            .col &nbsp;
        .row-group
          - (1...10).to_a.each do |index|
            .row
              .col.sort-handle
              .col= Faker::Name.first_name
              .col= Faker::Name.last_name
              .col= Faker::Internet.email
              .col= Faker::Internet.user_name
              .col.actions
                = button_group do
                  = edit_button_link_to "Edit preview", "#", :class => "accordion-toggle"
                  =# remove_row("#")
              .details
                %ul.table
                  %li This is an accordion aaaight!!
  -
=# render :partial => "sample/examples/table_basic"

= render :partial => "sample/examples/block_controls_tableless"



-#= adminv_container :width => :with_sidebar do |container|
  = container.table do |table|
    = table.header "Users"
    .table.accordion
      .header-group
        .row
          .col ID
          .col First Name
          .col Last Name
          .col Email
          .col Username
          .col &nbsp;
      .row-group
        - (1...10).to_a.each do |index|
          .row
            .col= index
            .col= Faker::Name.first_name
            .col= Faker::Name.last_name
            .col= Faker::Internet.email
            .col= Faker::Internet.user_name
            .col.actions
              = button_group do
                = edit_button_link_to "Edit preview", "#", :class => "accordion-toggle"
                =# remove_row("#")
            .details
              %ul.table
                %li This is an accordion aaaight!!
      .footer-group
        .row
          .col Col 1
          .col Col 2
          .col Col 3
          .col Col 4
          .col Col 5
          .col Col 6